-- MySQL Script generated by MySQL Workbench
-- 06/06/17 14:02:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_system` DEFAULT CHARACTER SET utf8 ;
USE `db_system` ;

-- -----------------------------------------------------
-- Table `db_system`.`system_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system`.`system_user` (
  `id_system_user` INT NOT NULL AUTO_INCREMENT,
  `system_user_email` VARCHAR(100) NULL,
  `system_user_password` VARCHAR(100) NULL,
  `system_user_level` VARCHAR(45) NULL,
  `system_user_status` VARCHAR(45) NULL,
  `system_user_name` VARCHAR(100) NULL,
  `system_user_phone` VARCHAR(21) NULL,
  `system_user_code` VARCHAR(45) NULL,
  `system_user_date` DATE NULL,
  `system_user_image` VARCHAR(45) NULL,
  `system_user_datetime_register` DATETIME NULL,
  `system_user_datetime_login` DATETIME NULL,
  `system_user_ip` VARCHAR(45) NULL,
  PRIMARY KEY (`id_system_user`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db_system`.`web_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system`.`web_account` (
  `id_web_account` INT(11) NOT NULL AUTO_INCREMENT,
  `web_account_status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_web_account`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_system`.`web_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system`.`web_user` (
  `id_web_user` INT(11) NOT NULL AUTO_INCREMENT,
  `id_system_user` INT(11) NOT NULL,
  `id_web_global` INT(11) NOT NULL,
  PRIMARY KEY (`id_web_user`),
  INDEX `fk_web_user_system_user1_idx` (`id_system_user` ASC),
  INDEX `fk_web_user_web_global1_idx` (`id_web_global` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_system`.`web_module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system`.`web_module` (
  `id_web_module` INT(11) NOT NULL AUTO_INCREMENT,
  `web_module_attribute` VARCHAR(45) NULL,
  `web_module_description` VARCHAR(100) NULL,
  `web_module_status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_web_module`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_system`.`web_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system`.`web_service` (
  `id_web_global_account` INT(11) NOT NULL AUTO_INCREMENT,
  `id_web_module` INT(11) NOT NULL,
  `id_web_account` INT(11) NOT NULL,
  PRIMARY KEY (`id_web_global_account`),
  INDEX `fk_web_global_account_web_software1_idx` (`id_web_module` ASC),
  INDEX `fk_web_global_account_web_global1_idx` (`id_web_account` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_system`.`system_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system`.`system_log` (
  `id_system_log` INT NOT NULL AUTO_INCREMENT,
  `id_system_user` INT NOT NULL,
  `system_log_datetime` DATETIME NULL,
  PRIMARY KEY (`id_system_log`),
  INDEX `fk_system_log_system_user1_idx` (`id_system_user` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_system`.`desktop_software`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system`.`desktop_software` (
  `id_desktop_software` INT(11) NOT NULL AUTO_INCREMENT,
  `desktop_software_attribute` VARCHAR(45) NULL,
  `desktop_software_description` VARCHAR(45) NULL,
  `desktop_software_status` VARCHAR(45) NULL,
  `desktop_software_version` VARCHAR(45) NULL,
  `desktop_software_message` VARCHAR(45) NULL,
  `desktop_software_link` VARCHAR(45) NULL,
  `desktop_software_value` VARCHAR(45) NULL,
  PRIMARY KEY (`id_desktop_software`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_system`.`system_download`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system`.`system_download` (
  `system_download_attribute` VARCHAR(45) NOT NULL DEFAULT '0',
  `system_download_date` DATE NOT NULL DEFAULT '0000-00-00',
  `system_download_number` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`system_download_attribute`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_system`.`system_feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system`.`system_feedback` (
  `system_feedback_attribute` VARCHAR(45) NOT NULL DEFAULT '0',
  `system_feedback_date` DATE NOT NULL DEFAULT '0000-00-00',
  `system_feedback_number` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`system_feedback_attribute`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_system`.`desktop_validation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system`.`desktop_validation` (
  `id_desktop_validation` INT(11) NOT NULL AUTO_INCREMENT,
  `id_desktop_software` INT(11) NOT NULL,
  `id_system_user` INT(11) NOT NULL,
  `desktop_validation_serial` VARCHAR(100) NULL,
  `desktop_validation_status` VARCHAR(45) NULL,
  `desktop_validation_activation` VARCHAR(45) NULL,
  `desktop_validation_system` VARCHAR(100) NULL,
  `desktop_validation_systemtype` VARCHAR(45) NULL,
  `desktop_validation_username` VARCHAR(45) NULL,
  `desktop_validation_version` VARCHAR(45) NULL,
  `desktop_validation_ip` VARCHAR(45) NULL,
  `desktop_validation_processor` VARCHAR(45) NULL,
  `desktop_validation_rammemory` VARCHAR(45) NULL,
  PRIMARY KEY (`id_desktop_validation`),
  INDEX `fk_desktop_validation_desktop_software1_idx` (`id_desktop_software` ASC),
  INDEX `fk_desktop_validation_system_user1_idx` (`id_system_user` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_system`.`support_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system`.`support_category` (
  `id_support_category` INT(11) NOT NULL,
  `support_category_attribute` VARCHAR(45) NULL,
  `support_category_description` VARCHAR(100) NULL,
  `support_category_status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_support_category`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_system`.`support_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system`.`support_ticket` (
  `id_support_ticket` INT(11) NOT NULL AUTO_INCREMENT,
  `id_support_category` INT(11) NOT NULL,
  `id_system_user` INT(11) NOT NULL,
  `support_ticket_subject` VARCHAR(45) NULL,
  `support_ticket_status` VARCHAR(45) NULL,
  `support_ticket_datetime_open` DATETIME NULL,
  `support_ticket_datetime_close` DATETIME NULL,
  PRIMARY KEY (`id_support_ticket`),
  INDEX `fk_support_ticket_support_category1_idx` (`id_support_category` ASC),
  INDEX `fk_support_ticket_system_user1_idx` (`id_system_user` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_system`.`support_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system`.`support_message` (
  `id_support_message` INT NOT NULL,
  `id_support_ticket` INT(11) NOT NULL AUTO_INCREMENT,
  `id_system_user` INT(11) NOT NULL,
  `support_message` LONGTEXT NULL,
  `support_message_file` BLOB NULL,
  `support_message_datetime` DATETIME NULL,
  PRIMARY KEY (`id_support_message`),
  INDEX `fk_support_message_support_ticket1_idx` (`id_support_ticket` ASC),
  INDEX `fk_support_message_system_user1_idx` (`id_system_user` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
